Repository equinor/webviz-subsurface-components, pull requests merged in 2021-08, with the labels that each got.

#479 Fixed infocard issue for multiple key in table
  react/src/lib/components/DeckGLMap/components/InfoCard.tsx
Labels: Emerson, bug, map-component

#480 Disable click propagation from information card to drawing layer
  react/src/lib/components/DeckGLMap/DeckGLMap.jsx
  react/src/lib/components/DeckGLMap/Map.tsx
  react/src/lib/components/DeckGLMap/components/InfoCard.tsx
Labels: Emerson, map-component

#484 Fix dependabot warning
  react/package-lock.json
Labels: maintenance, Emerson

#482 Bumped addon-redux dependency #481.
  react/package.json
  react/src/lib/components/DeckGLMap/redux/store.ts
  react/src/lib/components/GroupTree/redux/store.ts
  react/src/lib/components/WellCompletions/redux/store.ts
  react/src/lib/components/WellCompletions/test/storybookReduxAddon.ts
  react/src/lib/components/WellCompletions/test/storybookReduxAddon.tsx
Labels: maintenance, Emerson

#483 Change tsconfig flags to match Webviz Core Components
  react/.eslintrc
  react/package-lock.json
  react/package.json
  react/src/custom.d.ts
  react/src/lib/components/DeckGLMap/Map.tsx
  react/src/lib/components/DeckGLMap/components/settings/Settings.tsx
  react/src/lib/components/DeckGLMap/layers/drawing/drawingLayer.tsx
  react/src/lib/components/DeckGLMap/layers/fault_polygons/faultPolygonsLayer.ts
  react/src/lib/components/DeckGLMap/layers/piechart/pieChartLayer.ts
  react/src/lib/components/DeckGLMap/layers/utils/layerTools.ts
  react/src/lib/components/DeckGLMap/layers/wells/utils/spline.ts
  react/src/lib/components/DeckGLMap/layers/wells/wellsLayer.ts
  react/src/lib/components/DeckGLMap/redux/middleware.ts
  react/src/lib/components/DeckGLMap/redux/reducer.ts
  react/src/lib/components/DeckGLMap/utils/specExtractor.ts
  react/src/lib/components/GroupTree/components/Settings/DateTimeSlider.test.tsx
  react/src/lib/components/GroupTree/components/Settings/FlowRateSelector.test.tsx
  react/src/lib/components/GroupTree/components/Settings/FlowRateSelector.tsx
  react/src/lib/components/VectorSelector/components/VectorSelectorComponent.tsx
  react/src/lib/components/WellCompletions/components/Plot/plotUtil.ts
  react/src/lib/components/WellCompletions/components/Settings/FilterButton.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/FilterButton.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/HideZeroCompletionsSwitch.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/HideZeroCompletionsSwitch.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/SettingsBar.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/SortButton.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/SortButton.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/SortTable.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/SortTable.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/TimeAggregationSelector.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/TimeAggregationSelector.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/TimeRangeSelector.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/TimeRangeSelector.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/ViewButton.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/ViewButton.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellAttributesSelector.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellAttributesSelector.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellFilter.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellFilter.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellPagination.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellPagination.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellsPerPageSelector.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellsPerPageSelector.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/ZoneSelector.stories.tsx
  react/src/lib/components/WellCompletions/components/Settings/ZoneSelector.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/ZoneSelector.tsx
  react/src/lib/components/WellCompletions/redux/actions.test.ts
  react/src/lib/components/WellCompletions/redux/reducer.ts
  react/src/lib/components/WellCompletions/utils/dataUtil.ts
  react/src/lib/components/WellLogViewer/WellLogViewer.tsx
  react/src/lib/components/WellLogViewer/components/WellLogView.tsx
  react/src/lib/components/WellLogViewer/utils/tracks.ts
  react/tsconfig.json
Labels: maintenance, Emerson

#478 Map component tests
  react/src/lib/components/DeckGLMap/components/settings/DrawModeSelector.test.tsx
  react/src/lib/components/DeckGLMap/components/settings/LayerSettingsButton.test.tsx
  react/src/lib/components/DeckGLMap/components/settings/LayersButton.test.tsx
  react/src/lib/components/DeckGLMap/components/settings/Settings.test.tsx
  react/src/lib/components/DeckGLMap/components/settings/__snapshots__/DrawModeSelector.test.tsx.snap
  react/src/lib/components/DeckGLMap/components/settings/__snapshots__/LayerSettingsButton.test.tsx.snap
  react/src/lib/components/DeckGLMap/components/settings/__snapshots__/Settings.test.tsx.snap
  react/src/lib/components/DeckGLMap/test/TestWrapper.tsx
  react/src/lib/components/DeckGLMap/test/testReduxState.ts
Labels: Emerson, tests

#494 Merge well log type fixes
  react/src/lib/components/WellLogViewer/WellLogViewer.tsx
  react/src/lib/components/WellLogViewer/components/WellLogTemplateTypes.ts
  react/src/lib/components/WellLogViewer/components/WellLogTypes.ts
  react/src/lib/components/WellLogViewer/components/WellLogView.tsx
  react/src/lib/components/WellLogViewer/utils/tracks.ts
Labels: maintenance, Emerson

#498 Add all the needed files in the npm package
  react/package.json
  react/tsconfig.json
Labels: maintenance, Emerson

#499 Map component tests
  react/src/lib/components/DeckGLMap/test/TestWrapper.tsx
  react/src/lib/components/DeckGLMap/test/testReduxState.ts
Labels: Emerson, map-component, tests

#501 Update packages to fix dependabot alert
  react/package-lock.json
Labels: maintenance, Emerson

#510 Fix Well Log size issues
  examples/example_well_logs.py
  react/src/lib/components/WellLogViewer/WellLogViewer.tsx
  react/src/lib/components/WellLogViewer/components/WellLogView.tsx
  react/src/lib/components/WellLogViewer/components/styles.scss
Labels: Emerson, well-log-viewer

#511 Add comments to the map component
  README.md
  examples/example_deckgl_map.py
  react/src/lib/components/DeckGLMap/DeckGLMap.jsx
  react/src/lib/components/DeckGLMap/components/Map.tsx
  react/src/lib/components/DeckGLMap/layers/colormap/colormap.fs.glsl
  react/src/lib/components/DeckGLMap/layers/colormap/colormapLayer.ts
  react/src/lib/components/DeckGLMap/layers/drawing/drawingLayer.tsx
  react/src/lib/components/DeckGLMap/layers/hillshading2d/hillshading2d.fs.glsl
  react/src/lib/components/DeckGLMap/layers/hillshading2d/hillshading2dLayer.ts
  react/src/lib/components/DeckGLMap/layers/shader_modules/decoder.fs.glsl
  react/src/lib/components/DeckGLMap/layers/shader_modules/decoder.ts
  react/src/lib/components/DeckGLMap/layers/utils/layerTools.ts
  react/src/lib/components/DeckGLMap/layers/utils/propertyMapTools.ts
  react/src/lib/components/DeckGLMap/utils/configuration.ts
Labels: Emerson, map-component

#495 Map component storybook
  react/.storybook/addons.js
  react/.storybook/main.js
  react/package.json
  react/src/demo/DeckGLMapDemo.js
  react/src/demo/example-data/deckgl-map-spec.json
  react/src/lib/components/DeckGLMap/DeckGLMap.jsx
  react/src/lib/components/DeckGLMap/components/InfoCard.tsx
  react/src/lib/components/DeckGLMap/components/Map.tsx
  react/src/lib/components/DeckGLMap/components/settings/DrawModeSelector.tsx
  react/src/lib/components/DeckGLMap/components/settings/LayerSettingsButton.tsx
  react/src/lib/components/DeckGLMap/layers/colormap/colormap.fs.glsl
  react/src/lib/components/DeckGLMap/layers/hillshading2d/hillshading2d.fs.glsl
  react/src/lib/components/DeckGLMap/layers/shader_modules/decoder.fs.glsl
  react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
  react/src/lib/components/DeckGLMap/storybook/components/InfoCard.stories.jsx
  react/src/lib/components/DeckGLMap/storybook/components/Map.stories.jsx
  react/src/lib/components/DeckGLMap/storybook/components/settings/DrawModeSelector.stories.jsx
  react/src/lib/components/DeckGLMap/storybook/components/settings/LayerSettingsButton.stories.jsx
  react/src/lib/components/DeckGLMap/storybook/components/settings/LayersButton.stories.jsx
  react/src/lib/components/DeckGLMap/storybook/components/settings/Settings.stories.jsx
  react/src/lib/components/LayeredMap/shaders/fragmentShaderWithHillshading.fs.glsl
  react/src/lib/components/LayeredMap/shaders/fragmentShaderWithoutHillshading.fs.glsl
  react/src/lib/components/LayeredMap/shaders/vertexShader.vs.glsl
  react/src/lib/components/LeafletMap/shaders/position.vs.glsl
  react/src/lib/components/LeafletMap/shaders/terrainRGB.fs.glsl
  react/webpack.config.js
Labels: map-component
