Repository equinor/webviz-subsurface-components, pull requests merged in 2023-10, with the labels that each got.

#1677 docs: updated npm package badges
  README.md
Labels: AspenTech

#1682 fix: "IsRenderedCallack" shold return true for layers which has visib…
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: bug, AspenTech, map-component

#1685 fix: invalid capital IF in workflow job
  .github/workflows/python.yml
Labels: bug

#1686 fix: inject version in CI, adjust description, and add project URL
  .github/workflows/python.yml
  python/package.json
  python/setup.py
Labels: bug

#1688 feat(grid3d): constant color for coloring Grid3dLayer
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
Labels: enhancement, AspenTech, map-component

#1689 perf: Performance improvements to makeFullMesh function in MapLayer #1662
  typescript/packages/subsurface-viewer/src/layers/map/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/map/fragment_lines.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/map/mapLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/layers/map/mapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/utils.ts
  typescript/packages/subsurface-viewer/src/layers/map/webworker.ts
Labels: enhancement, AspenTech, map-component

#1694 chore: bump sass-loader dev dependency
  typescript/package-lock.json
  typescript/package.json
Labels: dependencies

#1696 build: Bump Deck.gl to latest version.
  typescript/package-lock.json
  typescript/packages/subsurface-viewer/package.json
Labels: dependencies, AspenTech, map-component

#1691 fix: View resets to default when adding/removing a layer. #1690
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.stories.tsx
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: bug, AspenTech, map-component

#1707 fix: audit fix prod dependencies
  typescript/package-lock.json
Labels: dependencies, AspenTech

#1714 feat: Grid3d Layer API and cursor readout enhancements.
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/vertex.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/webworker.ts
Labels: bug, enhancement, AspenTech, map-component

#1726 fix: prevent situation where width is defined and 0
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: bug, AspenTech, map-component

#1693 feat: Enhanced "refine" keyword for wells.
  typescript/packages/subsurface-viewer/src/layers/wells/utils/generateSynteticWell.ts
  typescript/packages/subsurface-viewer/src/layers/wells/utils/spline.test.ts
  typescript/packages/subsurface-viewer/src/layers/wells/utils/spline.ts
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
Labels: enhancement, AspenTech, map-component

#1737 perf: Apply flag "ZIncreasingDownwards" in vertex shaders for relevant layers. #1724
  typescript/packages/subsurface-viewer/src/layers/triangle/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/privateTriangleLayer.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/triangleLayer.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/vertex.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/vertex_lines.glsl.ts
Labels: enhancement, AspenTech, map-component

#1741 perf: Apply flag "ZIncreasingDownwards" in vertex shaders MapLayer.
  typescript/packages/subsurface-viewer/src/layers/map/mapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/utils.ts
  typescript/packages/subsurface-viewer/src/layers/map/vertex.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/map/vertex_lines.glsl.ts
Labels: enhancement, AspenTech, map-component
