Repository equinor/webviz-subsurface-components, pull requests merged in 2023-11, with the labels that each got.

#1744 ci: change storybook deploy destination directory
  .github/workflows/typescript.yml
Labels: AspenTech

#1746 ci: clean gh pages before deploy
  .github/workflows/typescript.yml
Labels: AspenTech

#1745 build(deps-dev): remove unused babel dev dependencies
  typescript/package-lock.json
  typescript/package.json
Labels: dependencies, AspenTech

#1755 test: fix storybook test runner
  .github/workflows/typescript.yml
Labels: AspenTech, tests

#1757 ci: remove redundant dependency install in ci
  .github/workflows/typescript.yml
Labels: AspenTech, tests

#1762 fix: If camera or bounds property is set, the view should not change when adding a layer.
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/layers/map/mapLayer.stories.tsx
Labels: bug, AspenTech, map-component

#1766 fix: "Grid3DLayer: surfaces are not displayed on firefox"
  typescript/packages/subsurface-viewer/src/layers/grid3d/webworker.ts
Labels: bug, AspenTech, map-component

#1768 fix: Point layer and line layer cursor readout not working
  typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.ts
  typescript/packages/subsurface-viewer/src/layers/polylines/polylinesLayer.ts
Labels: bug, AspenTech, map-component

#1769 fix: honor deck.gl extensions in MapLayer
  typescript/packages/subsurface-viewer/src/layers/map/mapLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/layers/map/mapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/vertex.glsl.ts
Labels: bug, AspenTech

#1770 fix: bump to latest @emerson-eps/color-tables
  typescript/package-lock.json
  typescript/packages/subsurface-viewer/package.json
  typescript/packages/well-log-viewer/package.json
Labels: bug, AspenTech

#1772 feat: Side projection extension
  typescript/packages/subsurface-viewer/src/extensions/side-projection-extension.stories.tsx
  typescript/packages/subsurface-viewer/src/extensions/side-projection-extension.ts
Labels: enhancement, AspenTech

#1776 feat: Enable left click to specify camera anchor/rotation point #1775
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: enhancement, AspenTech, map-component

#1787 feat(PointsLayer): ZIncreasingDownwards is applied in vertex shader, depthTest flag added
  typescript/packages/subsurface-viewer/src/layers/points/fragment.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.ts
  typescript/packages/subsurface-viewer/src/layers/points/privatePointsLayer.ts
  typescript/packages/subsurface-viewer/src/layers/points/vertex.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
Labels: enhancement, AspenTech, map-component

#1786 fix: Refill SyncLogViewer vew callbacks array on template array changing
  typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.tsx
Labels: AspenTech, well-log-viewer
