Repository equinor/webviz-subsurface-components, pull requests merged in 2023-09, with the labels that each got.

#1648 fix: MapLayer - null meshData values are treated as 0 #1642
  typescript/packages/subsurface-viewer/src/layers/map/webworker.ts
Labels: bug, AspenTech, map-component

#1647 refactor: Fix of [NGRM] - move shader code to local shader module #1646
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/shader_modules/decoder.ts
  typescript/packages/subsurface-viewer/src/layers/shader_modules/index.ts
  typescript/packages/subsurface-viewer/src/layers/shader_modules/lighting.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/shader_modules/localPhongLighting.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/privateTriangleLayer.ts
Labels: AspenTech, map-component

#1643 build: validate PR titles instead of commit messages
  .github/workflows/conventional_commit.yml
Labels: AspenTech

#1649 build: disable nx semantic release dry-run
  typescript/.nxreleaserc.json
Labels: AspenTech

#1652 fix: Prevent possible Nan values if viewport has zero width an…
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: bug, AspenTech, map-component

#1656 fix: Improve "isLoadedCallback" to not return true before first dra…
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/privateTriangleLayer.ts
Labels: enhancement, AspenTech, map-component

#1660 build: prevent persisting default GitHub token in semantic release
  .github/workflows/semantic_release.yml
Labels: AspenTech

#1661 build: add NODE_AUTH_TOKEN to semantic release
  .github/workflows/semantic_release.yml
Labels: AspenTech

#1663 build: fix build target option in semantic release config
  typescript/.nxreleaserc.json
Labels: AspenTech

#1664 build: use "package_name@version" tag format in semantic release
  typescript/.nxreleaserc.json
Labels: AspenTech

#1666 build: use --allow-same-version for "npm version"
  .github/workflows/webviz-subsurface-components.yml
Labels: AspenTech

#1668 fix: Rename callback to more descriptive name. Also callback should be…
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.stories.tsx
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: bug, AspenTech, map-component

#1670 build: added dependabot config
  .github/dependabot.yml
Labels: bug, dependencies, AspenTech

#1676 build(deps-dev): remove some unused dependencies
  typescript/package-lock.json
  typescript/package.json
Labels: dependencies, AspenTech

#1667 fix: Remove duplicate vertices from well path. May cause crash
  typescript/packages/subsurface-viewer/src/layers/wells/utils/generateSynteticWell.ts
  typescript/packages/subsurface-viewer/src/layers/wells/utils/spline.test.ts
  typescript/packages/subsurface-viewer/src/layers/wells/utils/spline.ts
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
Labels: bug, AspenTech, map-component
