Repository equinor/webviz-subsurface-components, pull requests merged in 2023-08, with the labels that each got.

#1624 feat(grid3d): prop to show-hide grid lines added
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
Labels: enhancement, AspenTech, map-component

#1635 build: add conventional commit commitlint
  .husky/commit-msg
  typescript/commitlint.config.js
  typescript/package-lock.json
  typescript/package.json
Labels: AspenTech

#1640 Add showLabels and showLines options for stacked track
  example-data/welllog_template_2.json
  typescript/packages/well-log-viewer/src/components/PlotDialog.tsx
  typescript/packages/well-log-viewer/src/components/TrackDialog.tsx
  typescript/packages/well-log-viewer/src/components/WellLogTemplateTypes.ts
  typescript/packages/well-log-viewer/src/utils/tracks.ts
  typescript/packages/wsc-common/src/inputSchema/WellLogTemplate.json
Labels: AspenTech, well-log-viewer

#1638 Semantic release dry-run
  .github/workflows/semantic_release.yml
  typescript/.nxreleaserc.json
  typescript/package-lock.json
  typescript/package.json
  typescript/packages/group-tree/project.json
  typescript/packages/subsurface-viewer/project.json
  typescript/packages/well-completions-plot/project.json
  typescript/packages/well-log-viewer/project.json
  typescript/packages/wsc-common/project.json
Labels: AspenTech

#1641 Refresh well log track title tooltip after interactive editing
  typescript/packages/well-log-viewer/src/components/WellLogView.tsx
  typescript/packages/well-log-viewer/src/utils/tracks.ts
Labels: AspenTech, well-log-viewer
