Repository equinor/webviz-subsurface-components, pull requests merged in 2023-06, with the labels that each got.

#1540 Closed polylines
  react/src/lib/components/SubsurfaceViewer/layers/polylines/polylinesLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/polylines/polylinesLayer.ts
Labels: enhancement, AspenTech, map-component

#1542 Side-independent lighting of surfaces in triangle layer
  react/src/lib/components/SubsurfaceViewer/layers/triangle/fragment.fs.glsl.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/privateTriangleLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/test_data/surfacePoints.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/test_data/surfaceTriangles.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/triangleLayer.stories.tsx
Labels: enhancement, AspenTech, map-component

#1555 Z scaling fix
  react/src/lib/components/SubsurfaceViewer/components/__snapshots__/Map.test.tsx.snap
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/components/__snapshots__/Map.test.tsx.snap
Labels: bug, AspenTech

#1547 Fix of "[NGRM] - Visual artifacts shown after setting incorrect matri…
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: bug, AspenTech, map-component

#1568 Migrate to Storybook 7
  typescript/.babelrc.json
  typescript/.storybook/main.js
  typescript/config/babel.config.json
  typescript/package-lock.json
  typescript/package.json
  typescript/packages/subsurface-viewer/package.json
  typescript/packages/well-completions/src/WellCompletions.stories.jsx
  typescript/packages/well-log-viewer/package.json
  typescript/packages/well-log-viewer/src/custom.d.ts
  typescript/storybook-static/favicon.ico
Labels: maintenance

#1572 Fix of "Crash in story "ViewMatrixMargin" #1571"
  typescript/packages/subsurface-viewer/src/storybook/SubsurfaceViewer.stories.jsx
Labels: bug, AspenTech, map-component

#1573 Restored typecheck and eslint
  .github/workflows/webviz-subsurface-components.yml
  typescript/.eslintignore
  typescript/custom.d.ts
  typescript/cypress.config.ts
  typescript/cypress/support/component.ts
  typescript/nx.json
  typescript/package-lock.json
  typescript/package.json
  typescript/packages/dash-components/src/DashSubsurfaceViewer.tsx
  typescript/packages/dash-components/src/VectorSelector/components/VectorSelectorComponent.tsx
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.stories.tsx
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/terrain/terrainMapLayer.ts
  typescript/packages/well-log-viewer/src/custom.d.ts
  typescript/tsconfig.json
Labels: maintenance

#1578 Remove "onMouseEvent" property from SubsurfaceViewer.propTypes
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
Labels: bug, AspenTech, map-component

#1579 Bump deck.gl to latest
  typescript/jest.config.js
  typescript/package-lock.json
  typescript/package.json
  typescript/packages/dash-components/webpack.config.js
  typescript/packages/subsurface-viewer/package.json
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.stories.tsx
  typescript/packages/subsurface-viewer/src/components/ColorLegend.test.tsx
  typescript/packages/subsurface-viewer/src/components/ColorLegend.tsx
  typescript/packages/subsurface-viewer/src/components/ColorLegends.test.tsx
  typescript/packages/subsurface-viewer/src/components/ColorLegends.tsx
  typescript/packages/subsurface-viewer/src/components/InfoCard.tsx
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/layers/BoxSelectionLayer/boxSelectionLayer.tsx
  typescript/packages/subsurface-viewer/src/layers/axes/axesLayer.ts
  typescript/packages/subsurface-viewer/src/layers/axes/boxLayer.ts
  typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
  typescript/packages/subsurface-viewer/src/layers/drawing/drawingLayer.tsx
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/mapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/northarrow/northArrow3DLayer.ts
  typescript/packages/subsurface-viewer/src/layers/piechart/pieChartLayer.ts
  typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.ts
  typescript/packages/subsurface-viewer/src/layers/polylines/polylinesLayer.ts
  typescript/packages/subsurface-viewer/src/layers/terrain/map3DLayer.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/privateTriangleLayer.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/triangleLayer.ts
  typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
  typescript/packages/subsurface-viewer/src/utils/specExtractor.ts
Labels: maintenance, AspenTech, map-component
