Repository equinor/webviz-subsurface-components, pull requests merged in 2023-02, with the labels that each got.

#1409 [NGRM] Bounds property is not respected when remounting component, #1408
  react/src/lib/components/SubsurfaceViewer/components/Map.tsx
Labels: bug, AspenTech, map-component

#1412 [NGRM] Bounds property is not respected when remounting component, #1408
  react/src/lib/components/SubsurfaceViewer/components/Map.tsx
Labels: bug, AspenTech, map-component

#1418 [NGRM] - Z values should be defined geological part 2. Rename "isZDep…
  react/src/lib/components/SubsurfaceViewer/layers/axes/axesLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/grid3d/fragment.fs.glsl.ts
  react/src/lib/components/SubsurfaceViewer/layers/grid3d/grid3dLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/wells/wellsLayer.ts
Labels: enhancement, AspenTech, map-component

#1413 Axes2D - Add non transparent background to the axes and add ability to set color on axes.
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/background-fragment.glsl.js
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/background-vertex.glsl.js
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/label-fragment.glsl.js
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/label-vertex.glsl.js
Labels: enhancement, AspenTech, map-component

#1416 Adding more props to continuous legend for dash support
  examples/example_webviz_continuouslegend.py
  react/src/lib/components/ColorLegends/WebVizContinuousLegend.tsx
Labels: AspenTech

#1419 The suggestions from Anders worked.
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.ts
Labels: enhancement, AspenTech, map-component

#1415 [NGRM] There should be an option to use constant color when coloring …
  react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/map/privateMapLayer.ts
Labels: enhancement, AspenTech, map-component

#1428 Fix of: "Axes2D - tick marcs are missing in story Wells/Volve wells 2…
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/wells/wellsLayer.stories.tsx
Labels: bug, AspenTech, map-component

#1435 Fix: "MapLayer shows dark when colorMapFunction or colorMapName are n…
  react/src/lib/components/SubsurfaceViewer/layers/map/privateMapLayer.ts
Labels: bug, AspenTech, map-component

#1433 Allow generic layers in SubsurfaceViewer
  react/src/lib/components/SubsurfaceViewer/SubsurfaceViewer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/SubsurfaceViewer.tsx
  react/src/lib/components/SubsurfaceViewer/components/Map.test.tsx
  react/src/lib/components/SubsurfaceViewer/components/Map.tsx
  react/src/lib/components/WellLogViewer/MapAndWellLogViewer.tsx
Labels: AspenTech, map-component

#1430 [NGRM] - New layer (TriangleLayer) to represent unstructured surfaces #1429
  react/src/lib/components/SubsurfaceViewer/layers/index.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/fragment.fs.glsl.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/fragment_lines.glsl.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/privateTriangleLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/triangleLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/triangle/triangleLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/vertex.glsl.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/vertex_lines.glsl.ts
  react/src/lib/components/SubsurfaceViewer/layers/triangle/webworker.ts
Labels: enhancement, AspenTech, map-component

#1439 Bump d3 dependency to latest.
  react/jest.config.js
  react/package-lock.json
  react/package.json
Labels: dependencies, AspenTech

#1437 Fix of: "[NGRM] - Axes2D. Add missing properties to set background an…
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/background-fragment.glsl.js
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/font-atlas.png
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/label-fragment.glsl.js
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/line-fragment.glsl.js
Labels: bug, AspenTech, map-component

#1441 Bump videx_wellog to latest.
  react/package-lock.json
  react/package.json
Labels: dependencies, AspenTech

#1444 Made more sensible default margins.
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.ts
Labels: enhancement, AspenTech
