Repository equinor/webviz-subsurface-components, pull requests merged in 2023-05, with the labels that each got.

#1491 Migrate SubsurfaceViewer to @mui
  react/package-lock.json
  react/package.json
  react/src/lib/components/SubsurfaceViewer/components/InfoCard.tsx
  react/src/lib/components/SubsurfaceViewer/components/ViewFooter.tsx
  react/src/lib/components/SubsurfaceViewer/components/__snapshots__/InfoCard.test.tsx.snap
  react/src/lib/components/SubsurfaceViewer/components/__snapshots__/ViewFooter.test.tsx.snap
  react/src/lib/components/SubsurfaceViewer/components/settings/LayerSettingsButton.tsx
  react/src/lib/components/SubsurfaceViewer/components/settings/LayersButton.tsx
  react/src/lib/components/SubsurfaceViewer/components/settings/Settings.tsx
  react/src/lib/components/SubsurfaceViewer/components/settings/__snapshots__/LayerSettingsButton.test.tsx.snap
  react/src/lib/components/SubsurfaceViewer/components/settings/__snapshots__/LayersButton.test.tsx.snap
  react/src/lib/components/SubsurfaceViewer/layers/BoxSelectionLayer/boxSelectionLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/terrain/map3DLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/wells/wellsLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/storybook/SubsurfaceViewer.stories.jsx
Labels: dependencies, AspenTech, map-component

#1490 Hook dependencies
  react/.eslintrc
  react/package.json
  react/src/lib/components/GroupTree/components/DataLoader.tsx
  react/src/lib/components/GroupTree/components/GroupTreeViewer.tsx
  react/src/lib/components/LeafletMap/components/Controls/components/Colorbar.js
  react/src/lib/components/LeafletMap/components/Controls/components/MousePosition.js
  react/src/lib/components/LeafletMap/components/Controls/components/ScaleControl.js
  react/src/lib/components/SubsurfaceViewer/SubsurfaceViewer.tsx
  react/src/lib/components/SubsurfaceViewer/components/ColorLegend.tsx
  react/src/lib/components/SubsurfaceViewer/components/DistanceScale.tsx
  react/src/lib/components/SubsurfaceViewer/components/Map.tsx
  react/src/lib/components/SubsurfaceViewer/components/settings/DrawModeSelector.tsx
  react/src/lib/components/SubsurfaceViewer/components/settings/LayerSettingsButton.tsx
  react/src/lib/components/SubsurfaceViewer/components/settings/LayersButton.tsx
  react/src/lib/components/SubsurfaceViewer/layers/BoxSelectionLayer/boxSelectionLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/terrain/map3DLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/wells/wellsLayer.stories.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/ExpressionEditComponent.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/ExpressionInputTextField.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/ExpressionNameTextField.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/MaxLengthTextField.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/VectorSelectorTable.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionsTableComponent/ExpressionsTableComponent.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionsTableComponent/components/ExpressionsTable.tsx
  react/src/lib/components/VectorCalculator/components/VectorCalculatorComponent.tsx
  react/src/lib/components/VectorCalculator/utils/ConfirmDialog.tsx
  react/src/lib/components/WellCompletions/components/Plot/CompletionsPlot.tsx
  react/src/lib/components/WellCompletions/components/Plot/WellsPlot.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellAttributesSelector.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellFilter.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellPagination.tsx
  react/src/lib/components/WellLogViewer/SyncLogViewer.stories.jsx
  react/src/lib/components/WellLogViewer/WellLogViewer.stories.jsx
Labels: enhancement, AspenTech, map-component

#1495 Axes bug
  react/src/lib/components/SubsurfaceViewer/layers/BoxSelectionLayer/boxSelectionLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/axes/axesLayer.ts
Labels: bug, AspenTech, map-component

#1508 Remove the state/useState "center" as it is not needed.
  react/src/lib/components/SubsurfaceViewer/components/Map.tsx
  react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
Labels: bug, map-component

#1497 Migrate GroupTree component to @mui
  react/src/lib/components/GroupTree/__snapshots__/GroupTree.test.tsx.snap
  react/src/lib/components/GroupTree/components/GroupTreeViewer.tsx
  react/src/lib/components/GroupTree/components/Settings/DateTimeSlider.test.tsx
  react/src/lib/components/GroupTree/components/Settings/DateTimeSlider.tsx
  react/src/lib/components/GroupTree/components/Settings/FlowRateSelector.tsx
  react/src/lib/components/GroupTree/components/Settings/NodeInfoSelector.tsx
  react/src/lib/components/GroupTree/components/Settings/SettingsBar.tsx
  react/src/lib/components/GroupTree/components/Settings/__snapshots__/DateTimeSlider.test.tsx.snap
  react/src/lib/components/GroupTree/components/Settings/__snapshots__/FlowRateSelector.test.tsx.snap
  react/src/lib/components/GroupTree/components/Settings/__snapshots__/NodeInfoSelector.test.tsx.snap
  react/src/lib/components/GroupTree/components/Settings/__snapshots__/SettingsBar.test.tsx.snap
  react/src/lib/components/GroupTree/components/__snapshots__/GroupTreeComponent.test.tsx.snap
  react/src/lib/components/GroupTree/components/__snapshots__/GroupTreeViewer.test.tsx.snap
Labels: maintenance, dependencies, AspenTech, group-tree

#1512 Added a story to demonstrate 2D axes in matrix mode.
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.stories.tsx
Labels: enhancement, AspenTech, map-component

#1514 Migrate WellCompletions to @mui
  react/package-lock.json
  react/package.json
  react/src/lib/components/WellCompletions/components/Common/ErrorPlaceholder.tsx
  react/src/lib/components/WellCompletions/components/Plot/WellCompletionsPlot.tsx
  react/src/lib/components/WellCompletions/components/Settings/SettingsBar.tsx
  react/src/lib/components/WellCompletions/components/Settings/SortButton.tsx
  react/src/lib/components/WellCompletions/components/Settings/SortTable.tsx
  react/src/lib/components/WellCompletions/components/Settings/TimeAggregationSelector.tsx
  react/src/lib/components/WellCompletions/components/Settings/TimeRangeSelector.test.tsx
  react/src/lib/components/WellCompletions/components/Settings/TimeRangeSelector.tsx
  react/src/lib/components/WellCompletions/components/Settings/ViewButton.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellAttributesSelector.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellFilter.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellPagination.tsx
  react/src/lib/components/WellCompletions/components/Settings/WellsPerPageSelector.tsx
  react/src/lib/components/WellCompletions/components/Settings/ZoneSelector.tsx
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/SettingsBar.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/SortButton.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/SortTable.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/TimeAggregationSelector.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/TimeRangeSelector.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/ViewButton.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/WellAttributesSelector.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/WellFilter.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/WellPagination.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/WellsPerPageSelector.test.tsx.snap
  react/src/lib/components/WellCompletions/components/Settings/__snapshots__/ZoneSelector.test.tsx.snap
  react/src/lib/components/WellCompletions/components/WellCompletionsViewer.tsx
  react/src/lib/components/WellCompletions/components/__snapshots__/WellCompletionComponent.test.tsx.snap
  react/src/lib/components/WellCompletions/components/__snapshots__/WellCompletionsViewer.test.tsx.snap
Labels: maintenance, dependencies, AspenTech, well-completions

#1507 [VITE] Removed inline-loaders and adjusted webpack config
  README.md
  react/package-lock.json
  react/package.json
  react/src/lib/components/GroupTree/components/GroupTreeViewer.tsx
  react/src/lib/components/Morris/Morris.jsx
  react/src/lib/components/PriorPosteriorDistribution/PriorPosteriorDistribution.jsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/ExpressionEditComponent.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/ExpressionDescriptionTextField.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/ExpressionInputTextField.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/ExpressionNameTextField.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/VectorSelectorTable.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionsTableComponent/ExpressionsTableComponent.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionsTableComponent/components/BlinkingTableRow.tsx
  react/src/lib/components/VectorCalculator/components/ExpressionsTableComponent/components/ExpressionsTable.tsx
  react/src/lib/components/VectorCalculator/components/VectorCalculatorComponent.tsx
  react/src/lib/components/WellCompletions/components/Settings/ZoneSelector.tsx
  react/src/lib/components/WellLogViewer/components/WellLogSpacer.tsx
  react/src/lib/components/WellLogViewer/components/WellLogView.tsx
  react/webpack.config.js
Labels: enhancement

#1503 [VITE] Missing export of `PickInfo` from `deck.gl` and `noImplicitAny`
  react/package-lock.json
  react/src/lib/components/SubsurfaceViewer/layers/BoxSelectionLayer/boxSelectionLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/BoxSelectionLayer/boxSelectionLayer.tsx
  react/src/lib/index.js
  react/tsconfig.json
Labels: bug, enhancement

#1501 [VITE] Missing types and type issues
  react/src/lib/components/ColorLegends/WebVizColorLegend.tsx
  react/src/lib/components/ColorLegends/WebVizContinuousLegend.tsx
  react/src/lib/components/SubsurfaceViewer/SubsurfaceViewer.tsx
  react/src/lib/components/SubsurfaceViewer/components/DistanceScale.tsx
  react/src/lib/components/SubsurfaceViewer/components/Map.tsx
  react/src/lib/components/SubsurfaceViewer/layers/axes/axesLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/map/webworker.ts
  react/src/lib/components/SubsurfaceViewer/layers/terrain/map3DLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/wells/wellsLayer.ts
Labels: bug

#1530 Fix of: "2D Axes are partly hidden initially on first render. #1529"
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/axes2DLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/background-fragment.glsl.js
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/background-vertex.glsl.js
  react/src/lib/components/SubsurfaceViewer/layers/axes2d/line-fragment.glsl.js
Labels: bug, AspenTech, map-component

#1528 Layers to display points and polylines.
  react/src/lib/components/SubsurfaceViewer/layers/index.ts
  react/src/lib/components/SubsurfaceViewer/layers/points/pointsLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/points/pointsLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/polylines/polylinesLayer.stories.tsx
  react/src/lib/components/SubsurfaceViewer/layers/polylines/polylinesLayer.ts
  react/src/lib/components/SubsurfaceViewer/layers/utils/layerTools.ts
Labels: AspenTech, map-component
