Repository equinor/webviz-subsurface-components, pull requests merged in 2024-09, with the labels that each got.

#2217 fix: Well Log Viewer - Moved callback subscription to well-log-viewer mounted hook
  typescript/packages/well-log-viewer/src/WellLogViewer.tsx
Labels: bug, well-log-viewer

#2153 fix: div size in the RTC Tab Layout story
  typescript/packages/well-log-viewer/src/Storybook/ExternalLayout.stories.tsx
  typescript/packages/well-log-viewer/src/Storybook/__image_snapshots__/welllogviewer-demo-classificationlayout--rtc-tabs-layout.png
  typescript/packages/well-log-viewer/src/components/WellLogLayout.scss
Labels: bug, AspenTech, well-log-viewer

#2227 fix(grid3): Grid3dLayer coloring by constant color fixed
  typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
Labels: bug, AspenTech, map-component

#2225 ci: prepare transition from nx-semantic-release to nx release
  .github/workflows/semantic_release.yml
  typescript/nx.json
  typescript/packages/group-tree-plot/project.json
  typescript/packages/subsurface-viewer/project.json
  typescript/packages/well-completions-plot/project.json
  typescript/packages/well-log-viewer/project.json
  typescript/packages/wsc-common/project.json
Labels: maintenance, AspenTech

#2234 fix(subsurface-viewer): fix color map sampling for 3D grids
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples--mixed-layer-definitions.png
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--continuous-property.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--custom-color-func-with-clamping.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--discrete-property.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--polyhedral-cells.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--simgrid-2-x.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--simgrid-4-x.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--simgrid-8-x-i-jonly.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--simgrid-array-input.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--simgrid.png
Labels: bug, AspenTech, map-component

#2233 docs: Update WellLogViewer documentation
  typescript/packages/well-log-viewer/src/Intro.mdx
Labels: well-log-viewer

#2248 fix: allow initializing scaling factor value
  typescript/packages/subsurface-viewer/src/utils/event.ts
Labels: bug, AspenTech, map-component

#2251 feat!: Refactor utils and provide WellCompletionsPlot utility-lib
  python/src/components/WellCompletions/components/DataLoader.tsx
  python/src/components/WellCompletions/components/Settings/SortTable.tsx
  python/src/components/WellCompletions/components/Settings/ZoneSelector.tsx
  python/src/components/WellCompletions/components/WellCompletionsViewer.tsx
  python/src/components/WellCompletions/hooks/usePlotData.tsx
  python/src/components/WellCompletions/utils/dataUtil.ts
  python/src/components/WellCompletions/utils/sort.ts
  typescript/packages/well-completions-plot/example-data/well-completions-plot-data.ts
  typescript/packages/well-completions-plot/src/WellCompletionsPlot.stories.tsx
  typescript/packages/well-completions-plot/src/WellCompletionsPlot.tsx
  typescript/packages/well-completions-plot/src/__image_snapshots__/wellcompletionsplot-demo--well-completions-plot-story.png
  typescript/packages/well-completions-plot/src/components/TooltipProvider.tsx
  typescript/packages/well-completions-plot/src/components/WellsPlot.tsx
  typescript/packages/well-completions-plot/src/index.ts
  typescript/packages/well-completions-plot/src/private-utils/layoutUtils.ts
  typescript/packages/well-completions-plot/src/private-utils/stringUtil.test.ts
  typescript/packages/well-completions-plot/src/private-utils/stringUtils.ts
  typescript/packages/well-completions-plot/src/types/dataTypes.ts
  typescript/packages/well-completions-plot/src/utility-lib/dataTypeUtils.test.ts
  typescript/packages/well-completions-plot/src/utility-lib/dataTypeUtils.ts
  typescript/packages/well-completions-plot/src/utility-lib/stringUtils.test.ts
  typescript/packages/well-completions-plot/src/utility-lib/stringUtils.ts
  typescript/packages/well-completions-plot/src/utility-lib/wellSortUtils.test.ts
  typescript/packages/well-completions-plot/src/utility-lib/wellSortUtils.ts
Labels: enhancement, CeeSol, well-completions

#2273 ci: add release rules for breaking "feat!" and "fix!" prefixes
  typescript/.nxreleaserc.json
Labels: maintenance, AspenTech

#2274 feat: Trigger release for new well-completions-plot package
  typescript/packages/well-completions-plot/src/components/WellsPlot.tsx
  typescript/packages/well-completions-plot/src/utility-lib/stringUtils.ts
Labels: enhancement, CeeSol

#2272 docs: Adjust incorrect storybook link in README file
  README.md
Labels: bug
