Repository equinor/webviz-subsurface-components, pull requests merged in 2024-06, with the labels that each got.

#2083 fix(Grid3D): crash in getPickingInfo fixed
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/test_data/DiscreteProperty/Props.json
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--custom-color-func-with-clamping.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--discrete-property-with-clamping.png
Labels: bug, AspenTech, map-component

#2084 fix(grid3d): getPickingInfo reworked.
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
Labels: bug, AspenTech, map-component

#2087 fix: Smooth SLV scrolling
  typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
  typescript/packages/well-log-viewer/src/components/CallbackManager.tsx
  typescript/packages/well-log-viewer/src/components/WellLogInfoPanel.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.tsx
  typescript/packages/well-log-viewer/src/components/WellLogViewWithScroller.tsx
  typescript/packages/well-log-viewer/src/utils/log-viewer.ts
Labels: AspenTech, well-log-viewer

#2091 fix(grid3d): faces are lighted by average normal.
  typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/vertex.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/webworker.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--discrete-property-with-clamping.png
Labels: enhancement, AspenTech, map-component

#2092 fix: "Incorrect depth readout in Grid3D layer after vertical re-scaling "
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/points/pointsLayer.ts
  typescript/packages/subsurface-viewer/src/layers/polylines/polylinesLayer.ts
  typescript/packages/subsurface-viewer/src/layers/triangle/privateTriangleLayer.ts
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
Labels: bug, AspenTech, map-component

#2107 fix(grid3d): Memory usage reduced.
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/typeDefs.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/webworker.ts
Labels: enhancement, AspenTech, map-component

#2122 fix: Crash Removing Well Log in SLV
  typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
Labels: bug, AspenTech, well-log-viewer
