Repository equinor/webviz-subsurface-components, pull requests merged in 2024-07, with the labels that each got.

#2135 fix: [NGRM] - Strange artefacts in 2D maps #2134
  example-data/ArtefactsMap/points.bin
  example-data/ArtefactsMap/properties.bin
  typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/vertex.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/map/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples--mixed-layer-definitions.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--add-layer.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--reset-camera-story.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--scale-z.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--synced-multi-view.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-mutiview--multi-view-annotation.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-mutiview--view-matrix-margin.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-mutiview--view-tabs.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-tooltip--mouse-event.png
  typescript/packages/subsurface-viewer/src/storybook/layers/MapLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--base.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--colored-text-and-back-ground.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--font-size.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--format-label-function.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--matrix.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer-colormap--color-selector.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer-colormap--step-function-color-map.png
Labels: bug, AspenTech

#2146 fix: Changed to low precission for uniform in grid3D layer.
  typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/vertex.glsl.ts
Labels: enhancement, AspenTech

#2150 fix: Fixes failing smoke test for axes2D layer.
  typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--format-label-function.png
Labels: bug, AspenTech

#2139 fix: StrictMode behaviour
  typescript/packages/well-log-viewer/src/Storybook/ExternalLayout.stories.tsx
  typescript/packages/well-log-viewer/src/SyncLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.tsx
  typescript/packages/well-log-viewer/src/components/DefaultSyncLogViewerLayout.tsx
  typescript/packages/well-log-viewer/src/components/WellLogAxesPanel.tsx
  typescript/packages/well-log-viewer/src/components/WellLogInfoPanel.tsx
  typescript/packages/well-log-viewer/src/components/WellLogScaleSelector.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.tsx
  typescript/packages/well-log-viewer/src/components/WellLogZoomSlider.tsx
  typescript/packages/well-log-viewer/src/utils/log-viewer.ts
Labels: bug, AspenTech, well-log-viewer

#2152 feat: color function (#2054)
  typescript/packages/well-log-viewer/src/WellLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.tsx
  typescript/packages/well-log-viewer/src/components/PlotDialog.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.tsx
  typescript/packages/well-log-viewer/src/utils/color-table.ts
  typescript/packages/well-log-viewer/src/utils/gradientfill-plot-legend.ts
  typescript/packages/well-log-viewer/src/utils/tracks.ts
Labels: enhancement, AspenTech, well-log-viewer
