Repository equinor/webviz-subsurface-components, pull requests merged in 2024-08, with the labels that each got.

#2197 feat(grid3d): Specific color for undefined property values.
  typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/webworker.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--discrete-property-with-undefined-values.png
Labels: enhancement, AspenTech, map-component

#2201 fix: remove defaultProps from function components
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
  typescript/packages/subsurface-viewer/src/components/DistanceScale.test.tsx
  typescript/packages/subsurface-viewer/src/components/DistanceScale.tsx
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/storybook/components/DistanceScale.stories.tsx
Labels: maintenance, AspenTech, map-component

#2200 build: (re)-introduce typechecking in stories
  typescript/.storybook/main.ts
  typescript/.storybook/test-runner.ts
  typescript/package.json
  typescript/packages/group-tree-plot/src/storybook/GroupTreePlot.stories.tsx
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.test.tsx
  typescript/packages/subsurface-viewer/src/components/StatusIndicator.test.tsx
  typescript/packages/subsurface-viewer/src/components/settings/LayersButton.test.tsx
  typescript/packages/subsurface-viewer/src/storybook/components/InfoCard.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/components/colorLegends/ContinuousLegend.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/components/colorLegends/DiscreteLegend.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/components/colorLegends/IndividualScaleForMap.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/components/colorLegends/SingleScaleForMap.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/MultiViewExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/RenderingExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/miscExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/extensions/SideProjectionExtension.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/MapLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/MapLayerColormap.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/schemaValidation/schemaValidation.stories.tsx
  typescript/packages/well-completions-plot/src/WellCompletionsPlot.stories.tsx
  typescript/packages/well-log-viewer/src/SyncLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/components/ScaleSelector.stories.tsx
  typescript/packages/well-log-viewer/src/components/Scroller.stories.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.stories.tsx
  typescript/packages/well-log-viewer/src/components/WellLogViewWithScroller.stories.tsx
  typescript/packages/well-log-viewer/src/components/ZoomSlider.stories.tsx
  typescript/tsconfig.eslint.json
Labels: AspenTech

#2202 docs: deprecate the editedData and related props
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: maintenance, AspenTech, map-component

#2206 build(deps-dev): bump @theunderscorer/nx-semantic-release
  typescript/package-lock.json
  typescript/package.json
Labels: dependencies, AspenTech

#2211 ci: revert release dependencies to previous working versions
  typescript/package-lock.json
  typescript/package.json
Labels: dependencies, AspenTech

#2213 test: re-enable skipped story smoke tests
  typescript/packages/subsurface-viewer/src/storybook/layers/AxesLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/MapLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/PointsLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/WellsLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axeslayer--custom-label.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--big-map-3-d.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--big-map-with-hole.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--big-map.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--contour-lines.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--extensions.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-2-d-dark-mode.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-2-d.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-3-d-png-no-bounds.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-3-d-png.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-with-artefacts.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--node-centered-prop-map.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--readout.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--rotated.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--typed-array-input.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-wells-layer--unfolded-projection.png
  typescript/packages/well-log-viewer/src/WellLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--color-by-function-tbd.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--default.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--discrete.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--horizontal.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--on-info-filled-event.png
Labels: AspenTech, tests
