Repository equinor/webviz-subsurface-components, pull requests merged in 2024-03, with the labels that each got.

#1941 feat: Track caption and readout font size and text truncation
  typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.tsx
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-synclogviewer--discrete-logs.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--default.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--discrete.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--horizontal.png
  typescript/packages/well-log-viewer/src/__snapshots__/SyncLogViewer.test.tsx.snap
  typescript/packages/well-log-viewer/src/__snapshots__/WellLogViewer.test.tsx.snap
  typescript/packages/well-log-viewer/src/components/AxisSelector.tsx
  typescript/packages/well-log-viewer/src/components/InfoPanel.tsx
  typescript/packages/well-log-viewer/src/components/InfoTypes.ts
  typescript/packages/well-log-viewer/src/components/WellLogSpacer.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.tsx
  typescript/packages/well-log-viewer/src/components/__image_snapshots__/welllogviewer-components-welllogview--default.png
  typescript/packages/well-log-viewer/src/components/__image_snapshots__/welllogviewer-components-welllogview--discrete.png
  typescript/packages/well-log-viewer/src/components/__image_snapshots__/welllogviewer-components-welllogviewwithscroller--default.png
  typescript/packages/well-log-viewer/src/components/__snapshots__/AxisSelector.test.tsx.snap
  typescript/packages/well-log-viewer/src/components/__snapshots__/InfoPanel.test.tsx.snap
  typescript/packages/well-log-viewer/src/components/__snapshots__/WellLogView.test.tsx.snap
  typescript/packages/well-log-viewer/src/components/__snapshots__/WellLogViewWithScroller.test.tsx.snap
  typescript/packages/well-log-viewer/src/components/rightPanel.scss
  typescript/packages/well-log-viewer/src/components/styles.scss
  typescript/packages/well-log-viewer/src/utils/fill-info.ts
  typescript/packages/well-log-viewer/src/utils/tracks.ts
Labels: enhancement, AspenTech, well-log-viewer

#1949 feat: PolylinesLayer typed arrays input.
  typescript/packages/subsurface-viewer/src/layers/polylines/path-layer-fragment.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/polylines/path-layer-vertex.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/polylines/polylinesLayer.ts
  typescript/packages/subsurface-viewer/src/layers/polylines/privatePolylinesLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/PolylinesLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-polylines-layer--huge-polylines-layer.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-polylines-layer--small-polylines-layer.png
Labels: enhancement, AspenTech, map-component

#1953 feat(grid3D): Support discrete properties.
  typescript/.eslintignore
  typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/test_data/DiscreteProperty/Points.json
  typescript/packages/subsurface-viewer/src/layers/grid3d/test_data/DiscreteProperty/Polys.json
  typescript/packages/subsurface-viewer/src/layers/grid3d/test_data/DiscreteProperty/Props.json
  typescript/packages/subsurface-viewer/src/layers/polylines/polylinesLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--discrete-property.png
Labels: enhancement, AspenTech, map-component

#1850 docs: Add testing to CONTRIBUTING.md checklist
  CONTRIBUTING.md
Labels: AspenTech

#1961 fix: "Not able to rotate/pan while loading layers. #1960"
  typescript/packages/subsurface-viewer/src/__snapshots__/SubsurfaceViewer.test.tsx.snap
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/components/__snapshots__/Map.test.tsx.snap
Labels: bug, AspenTech, map-component

#1963 fix: Wells does not update when property "wellNameAtTop" is changed #1962
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
Labels: bug, AspenTech, map-component

#1966 fix(grid3d): coloring by discrete property fixed.
  typescript/packages/subsurface-viewer/src/layers/grid3d/fragment.fs.glsl.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-grid3d-layer--discrete-property-with-clamping.png
Labels: bug, AspenTech, map-component

#1971 fix: "Incorrect 2D axes rendering with vertical scaling #1957"
  typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
  typescript/packages/subsurface-viewer/src/layers/axes2d/label-fragment.glsl.js
  typescript/packages/subsurface-viewer/src/layers/axes2d/label-vertex.glsl.js
  typescript/packages/subsurface-viewer/src/layers/axes2d/line-fragment.glsl.js
  typescript/packages/subsurface-viewer/src/layers/axes2d/line-vertex.glsl.js
  typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples--selectable-feature-example.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples--user-defined-layer-1.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples--user-defined-layer-2.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--scale-y.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-mutiview--synced-multi-view.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-mutiview--view-matrix-margin.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-mutiview--view-tabs.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--base.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--colored-text-and-back-ground.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--matrix.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-2-d.png
  typescript/packages/subsurface-viewer/src/storybook/sharedSettings.tsx
Labels: bug, AspenTech, map-component

#1978 fix: disable manipulation and fix matrix error before camera initialization
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/index.ts
  typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/MapLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/WellsLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/sharedSettings.tsx
  typescript/packages/subsurface-viewer/src/utils/BoundingBox2D.test.ts
  typescript/packages/subsurface-viewer/src/utils/BoundingBox2D.ts
  typescript/packages/subsurface-viewer/src/utils/BoundingBox3D.test.ts
  typescript/packages/subsurface-viewer/src/utils/BoundingBox3D.ts
Labels: AspenTech, map-component

#1980 test: allow running docker tests on Windows git bash shell
  typescript/Dockerfile.test
  typescript/package-lock.json
  typescript/package.json
Labels: AspenTech, tests
