Repository equinor/webviz-subsurface-components, pull requests merged in 2024-04, with the labels that each got.

#1904 feat: Added property "formatLabelFunc" to set a callback funtion for formating label numbers
  typescript/README.md
  typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--scale-y.png
  typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--base.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--format-label-function.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--matrix.png
Labels: enhancement, AspenTech

#2002 feat: Allow camera xy scaling
  typescript/packages/subsurface-viewer/package.json
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/index.ts
  typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--scale-y-with-camera-position.png
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--scale-y.png
  typescript/packages/subsurface-viewer/src/utils/camera.test.ts
  typescript/packages/subsurface-viewer/src/utils/camera.ts
  typescript/packages/well-log-viewer/package.json
  typescript/packages/wsc-common/package.json
Labels: AspenTech, map-component

#2012 feat(grid3d): discrete property names are displayed in the readouts.
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
Labels: enhancement, AspenTech, map-component

#2013 fix: honor vertical scale prop in 3D
  typescript/package-lock.json
  typescript/packages/subsurface-viewer/package.json
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/index.ts
  typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--scale-vertical-3-d.png
  typescript/packages/subsurface-viewer/src/utils/camera.test.ts
  typescript/packages/subsurface-viewer/src/utils/camera.ts
  typescript/packages/subsurface-viewer/src/utils/event.ts
  typescript/packages/subsurface-viewer/src/views/viewport.ts
Labels: AspenTech, map-component

#2016 feat: move vertical scale to SubsurfaceViewer props
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
  typescript/packages/subsurface-viewer/src/components/Map.tsx
  typescript/packages/subsurface-viewer/src/storybook/examples/CameraControlExamples.stories.tsx
  typescript/packages/subsurface-viewer/src/views/viewport.ts
Labels: AspenTech, map-component

#2026 feat: add abscissa transform utility function for wells
  typescript/packages/subsurface-viewer/package.json
  typescript/packages/subsurface-viewer/src/layers/index.ts
  typescript/packages/subsurface-viewer/src/layers/wells/utils/abscissaTransform.test.ts
  typescript/packages/subsurface-viewer/src/layers/wells/utils/abscissaTransform.ts
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/WellsLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-wells-layer--unfolded-projection.png
Labels: enhancement, AspenTech, map-component

#2024 fix: "[NGRM] - Axes2DLayer; Introduce a property "labelFontSizePt" to enable controlling the size of the labels"
  typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--font-size.png
Labels: enhancement, AspenTech, map-component

#2028 fix: Incorrect depth readout after vertical re-scaling
  typescript/packages/subsurface-viewer/src/layers/map/privateMapLayer.ts
Labels: bug, AspenTech, map-component

#2032 feat(grid3d): Discrete property value in grid readouts
  typescript/package.json
  typescript/packages/subsurface-viewer/src/layers/grid3d/grid3dLayer.ts
  typescript/packages/subsurface-viewer/src/layers/grid3d/privateGrid3dLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
Labels: enhancement, AspenTech, map-component

#2033 feat: add section projection option to wells layer
  typescript/packages/subsurface-viewer/src/layers/wells/utils/spline.test.ts
  typescript/packages/subsurface-viewer/src/layers/wells/utils/spline.ts
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/WellsLayer.stories.tsx
Labels: enhancement, AspenTech, map-component
