Repository equinor/webviz-subsurface-components, pull requests merged in 2024-10, with the labels that each got.

#2249 feat: ColorMapFunction type in WellLogView
  .gitignore
  example-data/facies3wells.json
  example-data/synclog_template.json
  example-data/welllog_template_1.json
  example-data/welllog_template_2.json
  example-data/wellpick_colors.json
  python/src/components/WellLogViewer/WellLogViewer.tsx
  typescript/packages/well-log-viewer/src/SyncLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/SyncLogViewer.test.tsx
  typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.test.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer_performance.test.tsx
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--color-by-function.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--discrete.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--horizontal.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--on-info-filled-event.png
  typescript/packages/well-log-viewer/src/components/ColorMapFunction.ts
  typescript/packages/well-log-viewer/src/components/ColorTableTypes.ts
  typescript/packages/well-log-viewer/src/components/CommonPropTypes.ts
  typescript/packages/well-log-viewer/src/components/InfoPanel.tsx
  typescript/packages/well-log-viewer/src/components/LocalMenus.tsx
  typescript/packages/well-log-viewer/src/components/PlotDialog.tsx
  typescript/packages/well-log-viewer/src/components/ScaleSelector.stories.tsx
  typescript/packages/well-log-viewer/src/components/ScaleSelector.tsx
  typescript/packages/well-log-viewer/src/components/Scroller.stories.tsx
  typescript/packages/well-log-viewer/src/components/Scroller.tsx
  typescript/packages/well-log-viewer/src/components/TrackDialog.tsx
  typescript/packages/well-log-viewer/src/components/WellLogSpacer.tsx
  typescript/packages/well-log-viewer/src/components/WellLogTemplateTypes.ts
  typescript/packages/well-log-viewer/src/components/WellLogTypes.ts
  typescript/packages/well-log-viewer/src/components/WellLogView.stories.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.test.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.tsx
  typescript/packages/well-log-viewer/src/components/WellLogViewWithScroller.stories.tsx
  typescript/packages/well-log-viewer/src/components/WellLogViewWithScroller.test.tsx
  typescript/packages/well-log-viewer/src/components/ZoomSlider.stories.tsx
  typescript/packages/well-log-viewer/src/components/ZoomSlider.tsx
  typescript/packages/well-log-viewer/src/utils/color-table.ts
  typescript/packages/well-log-viewer/src/utils/deepcopy.ts
  typescript/packages/well-log-viewer/src/utils/edit-track.tsx
  typescript/packages/well-log-viewer/src/utils/fill-info.ts
  typescript/packages/well-log-viewer/src/utils/gradientfill-plot-legend.ts
  typescript/packages/well-log-viewer/src/utils/gradientfill-plot.ts
  typescript/packages/well-log-viewer/src/utils/minmax.ts
  typescript/packages/well-log-viewer/src/utils/pattern.tsx
  typescript/packages/well-log-viewer/src/utils/tracks.ts
  typescript/packages/wsc-common/src/inputSchema/WellLogTemplate.json
Labels: enhancement, AspenTech, well-log-viewer

#2279 feat: Well log viewer - multiple well log support
  typescript/packages/well-log-viewer/src/Storybook/examples/MapAndWellLogViewer.tsx
  typescript/packages/well-log-viewer/src/SyncLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/SyncLogViewer.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.stories.tsx
  typescript/packages/well-log-viewer/src/WellLogViewer.tsx
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--color-by-function.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--default.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--discrete.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--horizontal.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--log-with-different-sets.png
  typescript/packages/well-log-viewer/src/__image_snapshots__/welllogviewer-demo-welllogviewer--on-info-filled-event.png
  typescript/packages/well-log-viewer/src/__snapshots__/SyncLogViewer.test.tsx.snap
  typescript/packages/well-log-viewer/src/__snapshots__/WellLogViewer.test.tsx.snap
  typescript/packages/well-log-viewer/src/components/CallbackManager.tsx
  typescript/packages/well-log-viewer/src/components/DefaultSyncLogViewerLayout.tsx
  typescript/packages/well-log-viewer/src/components/LocalMenus.tsx
  typescript/packages/well-log-viewer/src/components/PlotDialog.tsx
  typescript/packages/well-log-viewer/src/components/TrackDialog.tsx
  typescript/packages/well-log-viewer/src/components/WellLogAxesPanel.tsx
  typescript/packages/well-log-viewer/src/components/WellLogTypes.ts
  typescript/packages/well-log-viewer/src/components/WellLogView.stories.tsx
  typescript/packages/well-log-viewer/src/components/WellLogView.tsx
  typescript/packages/well-log-viewer/src/components/WellLogViewWithScroller.test.tsx
  typescript/packages/well-log-viewer/src/components/__image_snapshots__/welllogviewer-components-welllogview--default.png
  typescript/packages/well-log-viewer/src/components/__image_snapshots__/welllogviewer-components-welllogview--discrete.png
  typescript/packages/well-log-viewer/src/components/__image_snapshots__/welllogviewer-components-welllogviewwithscroller--default.png
  typescript/packages/well-log-viewer/src/utils/tracks.ts
  typescript/packages/well-log-viewer/src/utils/well-log.test.ts
  typescript/packages/well-log-viewer/src/utils/well-log.ts
  typescript/packages/well-log-viewer/tsconfig.json
Labels: enhancement, CeeSol, well-log-viewer

#2313 feat: expose `pickingRadius` as prop in `Map.tsx` in `SubsurfaceViewer` package
  typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: enhancement, CeeSol

#2314 fix: incorrect interface of `ColormapLayer`
  typescript/packages/subsurface-viewer/src/layers/colormap/colormapLayer.ts
  typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
Labels: bug

#2321 fix: Improve sort by stratigraphy depth in utility-lib for well-completions-plot
  typescript/packages/well-completions-plot/src/utility-lib/wellSortUtils.test.ts
  typescript/packages/well-completions-plot/src/utility-lib/wellSortUtils.ts
Labels: enhancement
