Repository equinor/webviz-subsurface-components, pull requests merged in 2024-02, with the labels that each got.

#1907 fix: Well head position Z value should match the top of the well trajectory by default if not set explicitly
  typescript/packages/subsurface-viewer/src/layers/wells/utils/spline.ts
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/WellsLayer.stories.tsx
Labels: AspenTech

#1923 build(deps-dev): remove some unused dev deps
  typescript/package-lock.json
  typescript/package.json
Labels: dependencies, AspenTech

#1932 fix: styles for track/plot dialog
  typescript/packages/well-log-viewer/src/components/PlotDialog.tsx
  typescript/packages/well-log-viewer/src/components/TrackDialog.tsx
Labels: enhancement, AspenTech, well-log-viewer
