Repository equinor/webviz-subsurface-components, pull requests merged in 2025-05, with the labels that each got.

#2544 fix: Disable depth test for cross-hair layer to always keep it at top
  typescript/packages/subsurface-viewer/src/layers/crosshair/crosshairLayer.ts
Labels: bug

#2549 ci: migrate to `nx release` for semantic releases
  .github/workflows/semantic_release.yml
  .github/workflows/typescript.yml
  typescript/package-lock.json
  typescript/package.json
  typescript/packages/group-tree-plot/package.json
  typescript/packages/group-tree-plot/project.json
  typescript/packages/subsurface-viewer/package.json
  typescript/packages/subsurface-viewer/project.json
  typescript/packages/well-completions-plot/package.json
  typescript/packages/well-completions-plot/project.json
  typescript/packages/well-log-viewer/package.json
  typescript/packages/well-log-viewer/project.json
  typescript/packages/wsc-common/package.json
  typescript/packages/wsc-common/project.json
Labels: maintenance, AspenTech

#2551 ci: fix syntax error in dependency install
  .github/workflows/semantic_release.yml
Labels: bug, AspenTech

#2552 ci: add working-directory to nx build step
  .github/workflows/semantic_release.yml
Labels: bug, AspenTech

#2553 ci: attempt to fix nx release github authentication
  .github/workflows/semantic_release.yml
  .github/workflows/typescript.yml
Labels: bug, AspenTech

#2554 ci: revert "chore(release): publish"
  typescript/package-lock.json
Labels: bug, AspenTech

#2555 ci: prevent corrupting package-lock.json in `nx release`.
  .github/workflows/semantic_release.yml
  typescript/package-lock.json
Labels: bug, AspenTech

#2556 fix: test package publishing using nx release
  typescript/packages/subsurface-viewer/src/layers/axes/axesLayer.ts
Labels: maintenance, AspenTech

#2557 ci: setup NPM authentication in node setup stage
  .github/workflows/semantic_release.yml
  .prettierrc
  prettier.config.js
  typescript/package.json
  typescript/packages/group-tree-plot/package.json
  typescript/packages/well-completions-plot/package.json
  typescript/packages/well-log-viewer/package.json
  typescript/packages/wsc-common/package.json
Labels: bug, AspenTech

#2560 build(deps-dev): bump nx to latest
  typescript/package-lock.json
  typescript/package.json
Labels: dependencies
