Repository equinor/webviz-subsurface-components, pull requests merged in 2025-04, with the labels that each got.

#2495 fix: Well label interpolation on sparse trajectories
  typescript/packages/subsurface-viewer/src/layers/wells/layers/wellLabelLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/constant/argTypes.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/WellLabelLayer.stories.tsx
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-well-label-layer--default.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-well-label-layer--label-auto-position.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-well-label-layer--label-position.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-well-label-layer--label-style.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-well-label-layer--sparse-label-position.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-well-label-layer--tangent-orientation.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-wells-layer--coarse-well-factor.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-wells-layer--well-label-style.png
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-wells-layer--wells-3-d.png
  typescript/packages/subsurface-viewer/src/storybook/types/trajectory.ts
Labels: bug, AspenTech, map-component

#2499 fix: prevent flipping well label z coordinates
  typescript/packages/subsurface-viewer/src/layers/wells/wellsLayer.ts
Labels: bug, AspenTech, map-component

#2493 ci: dry-run semantic release in PR validation
  .github/workflows/typescript.yml
  typescript/packages/group-tree-plot/package.json
  typescript/packages/subsurface-viewer/package.json
  typescript/packages/well-completions-plot/package.json
  typescript/packages/well-log-viewer/package.json
  typescript/packages/wsc-common/package.json
Labels: maintenance, AspenTech

#2520 fix: Made Well Log Viewer set correct bounds even if no tracks are present
  typescript/packages/well-log-viewer/src/utils/tracks.ts
Labels: CeeSol, well-log-viewer

#2513 fix: Fix model matrix
  typescript/packages/subsurface-viewer/src/components/Map.tsx
Labels: bug, AspenTech

#2526 fix(subsurface-viewer): prevent disappearing well label texts
  typescript/packages/subsurface-viewer/src/layers/wells/layers/wellLabelLayer.ts
  typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-well-label-layer--label-auto-position.png
Labels: bug, AspenTech, map-component

#2527 build(deps-dev): bump nx to latest
  typescript/package-lock.json
  typescript/package.json
Labels: maintenance, dependencies, AspenTech
